GET http://localhost:3000/api/products/1
Content-Type: application/json 

PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
    "name": "Product 1",
    "price": 10
}

DELETE http://localhost:3000/api/products/1

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Product 4",
    "price": 40
}
    